<?php
// $Id$
/**
* Implements hook_filter_info().
*/
function tbx_filters_filter_info() {
  $filters = array();
  $filters['filter_foo'] = array(
    'title' => t('Foo Filter (example)'),
    'description' => t('Every instance of "foo" in the input text will be replaced with a preconfigured replacement.'),
    'process callback'  => '_tbx_filters_process',
    'default settings' => array(
      'filter_example_foo' => 'bar',
    ),
  );

  return $filters;
}


/**
* Implements filter process callback.
*/
function _tbx_filters_process($text, $filter)  {
  return str_replace('IA', 'ZZZ', $text);
}


