<?php
// $Id$
/**
* Implements hook_filter_info().
*/
function tbx_filters_filter_info() {
  $filters = array();
  $filters['filter_foo'] = array(
    'title' => t('Foo Filter (example)'),
    'description' => t('Every instance of "foo" in the input text will be replaced with a preconfigured replacement.'),
    'process callback'  => '_tbx_filters_process',
    'default settings' => array(
      'filter_example_foo' => 'bar',
    ),
    'settings callback' => '_tbx_filters_settings',
    'tips callback' => '_tbx_filters_tips',
  );

  return $filters;
}
/**
* Implements filter prepare callback._tbx_filters_settings
*/
function _tbx_filters_settings() {
}

/**
* Implements filter process callback.
*/
function _tbx_filters_process() {
}

/**
* Implements filter tips callback.
*/
function _tbx_filters_tips() {
}